### ISSUE TITLE
Issue#6 -> new features

### ISSUE THREAD

**Issue by RigaNik** [neshkovac/restoran#11]
- [x] fixed navigation on scroll spy animation! (keep it fixed on top when scrolling down)
Let's try design for this fixed navigation: background-color: #c90; color: #fff; paddings randomly to look nice. @neshkovac 
- [x] Facebook OG tags add @neshkovac 
- [x] Back to top button @Pdavid8 
- [x] page speed -> now "gulp watch" serves on localhost:3000, you can download [page speed plugin ](https://chrome.google.com/webstore/detail/pagespeed-insights-with-p/lanlbpjbalfkflkhegagflkgcfklnbnh) - inspect element - page speed - run analyse. You can see how to improve page speed with this plugin. More info on page speed plugin page. @neshkovac @Pdavid8

**Comment by neshkovac** [comment]
Just ran the PageSpeed plugin, 75/100, saw the suggestions and will read upon them.
